# Default constants
DEFAULTS = {
    "time_horizon": 24,
    "time_step": 1.0,
    "ramp_up": 100.0,
    "ramp_down": 100.0,
    "startup_limit": 100.0,
    "shutdown_limit": 100.0,
    "min_uptime": 1,
    "min_downtime": 1,
    "normal_limit": 300.0,
    "emergency_limit": 400.0,
    "flow_penalty": 1000.0,
    "reserve_penalty": 100.0,
    "balance_penalty": 10000.0,
    "storage_charge_cost": 2.0,
    "storage_discharge_cost": 2.5,
    "storage_max_level": 100.0,
    "storage_charge_rate": 10.0,
    "storage_discharge_rate": 10.0,
    "storage_charge_eff": 0.9,
    "storage_discharge_eff": 0.9,
    "storage_loss_factor": 0.0,
    "storage_initial_level": 50.0,
    "cost_scale": 1000.0,  # Scale production costs to $/MWh
}

KEY_MAPPINGS = {
    "time_horizon": {"Time horizon (h)", "Time (h)"},
    "time_step": {"Time step (min)"},
    "p_mw": {"Production cost curve (MW)", "Maximum power (MW)", "Minimum power (MW)"},
    "p_cost": {"Production cost curve ($)", "Cost ($/MW)"},
    "bus": {"Bus"},
    "type": {"Type"},
    "startup_delays": {"Startup delays (h)"},
    "startup_costs": {"Startup costs ($)"},
    "ramp_up": {"Ramp up limit (MW)"},
    "ramp_down": {"Ramp down limit (MW)"},
    "startup_limit": {"Startup limit (MW)"},
    "shutdown_limit": {"Shutdown limit (MW)"},
    "must_run": {"Must run?"},
    "min_uptime": {"Minimum uptime (h)"},
    "min_downtime": {"Minimum downtime (h)"},
    "initial_status": {"Initial status (h)"},
    "initial_power": {"Initial power (MW)"},
    "reserve_eligibility": {"Reserve eligibility"},
    "commitment_status": {"Commitment status"},
    "load_mw": {"Load (MW)"},
    "source_bus": {"Source bus"},
    "target_bus": {"Target bus"},
    "reactance": {"Reactance (ohms)"},
    "susceptance": {"Susceptance (S)"},
    "normal_limit": {"Normal flow limit (MW)"},
    "emergency_limit": {"Emergency flow limit (MW)"},
    "flow_penalty": {"Flow limit penalty ($/MW)"},
    "reserve_amount": {"Amount (MW)"},
    "reserve_penalty": {"Shortfall penalty ($/MW)", "Reserve shortfall penalty ($/MW)"},
    "storage_min_level": {"Minimum level (MWh)"},
    "storage_max_level": {"Maximum level (MWh)"},
    "storage_charge_cost": {"Charge cost ($/MW)"},
    "storage_discharge_cost": {"Discharge cost ($/MW)"},
    "storage_charge_eff": {"Charge efficiency"},
    "storage_discharge_eff": {"Discharge efficiency"},
    "storage_loss_factor": {"Loss factor"},
    "storage_min_charge_rate": {"Minimum charge rate (MW)"},
    "storage_max_charge_rate": {"Maximum charge rate (MW)"},
    "storage_min_discharge_rate": {"Minimum discharge rate (MW)"},
    "storage_max_discharge_rate": {"Maximum discharge rate (MW)"},
    "storage_initial_level": {"Initial level (MWh)"},
    "storage_last_min_level": {"Last period minimum level (MWh)"},
    "storage_last_max_level": {"Last period maximum level (MWh)"},
    "storage_simultaneous": {"Allow simultaneous charging and discharging"},
    "min_power": {"Minimum power (MW)"},
    "max_power": {"Maximum power (MW)"},
}

def get_config(user_config=None):
    config = DEFAULTS.copy()
    if user_config:
        config.update(user_config)
    return config